spring:
  profiles.active: production

---

endpoints:
  info:
    enabled: true
    sensitive: false

  health:
    sensitive: false
    
  metrics:
    sensitive: false


spring:
    profiles: production
    application:
        name: cities-management-service 
    datasource:
        platform: h2
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:test;MODE=PostgreSQL  
    h2:
        console:
          enabled: true      
  
server:
    port:     8080  

eureka:
    client:
        serviceUrl:
            defaultZone:     ${EUREKA_URI:http://cities-services-registry:8770/eureka}
        healthcheck:
            enabled: true
        instance:
            leaseRenewalIntervalInSeconds: 15
            preferIpAddress:  true

